CREATE TABLE IF NOT EXISTS products (id INT AUTO_INCREMENT PRIMARY KEY, sku VARCHAR(100) UNIQUE, name VARCHAR(200), price INT, stock INT DEFAULT 100);
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(200) UNIQUE);
CREATE TABLE IF NOT EXISTS orders (orderId VARCHAR(50) PRIMARY KEY, status VARCHAR(20), total INT);
INSERT IGNORE INTO products (sku, name, price) VALUES ('soap-neem-100g','Neem Soap',99);